apiVersion: devices.kubeedge.io/v1alpha2
kind: Device
metadata:
  name: stwinkt1b-00112233ffee
  namespace: fluidos
  labels:
    description: Sensor-Tile-Board
    manufacturer: STMicroelectronics
    model: STWINKT1B
  annotations:
    sensors: WwogIHsKICAgICJ1aWQiOiAiMzFiYWNmMTctZjIxNy1hNmRkLTRmMWQtNDEzODdjNDBkZGI5IiwKICAgICJub2RlIjogIiIsCiAgICAibmFtZSI6ICJIVFMyMjEiLAogICAgIm1vZGVsIjogImh0czIyMSIsCiAgICAibWFudWZhY3R1cmVyIjogIlNUTWljcm9lbGVjcm9uaWNzIiwKICAgICJtYXJrZXQiOiAiQ29tbWVyY2lhbCIsCiAgICAidHlwZSI6IHsKICAgICAgInNlbnNvckNhdGVnb3J5IjogIkVudmlyb25tZW50YWwiLAogICAgICAic2Vuc29yVHlwZSI6IFsiVGVtcGVyYXR1cmUiLCAiSHVtaWRpdHkiXQogICAgfSwKICAgICJzYW1wbGluZ1JhdGUiOiAiMSIsCiAgICAiYWNjdXJhY3kiOiBbIjAuMSIsICIwLjUiXSwKICAgICJjb25zdW1wdGlvbiI6ICIwLjA2IiwKICAgICJsYXRlbmN5IjogIjEwMCIsCiAgICAicHJvcGVydGllcyI6IHsKICAgICAgInVuaXQiOiB7CiAgICAgICAgIm1lYXN1cmVtZW50IjogWyLCsEMiLCAiJSJdLAogICAgICAgICJjb25zdW1wdGlvbiI6ICJtVyIsCiAgICAgICAgInNhbXBsaW5nUmF0ZSI6ICJIeiIsCiAgICAgICAgImxhdGVuY3kiOiAibXMiCiAgICAgIH0KICAgIH0sCiAgICAiYWNjZXNzIjogewogICAgICAidHlwZSI6ICJNUVRUIiwKICAgICAgInNvdXJjZSI6ICJldmVudGJ1cy1mbHVpZG9zIiwKICAgICAgInJlc291cmNlIjogewogICAgICAgICJ0b3BpYyI6ICJzZW5zb3JzL0NCQjhDMjE1MTlFRi8wMDE0MDAwMDAwMDExMWUxYWMzNjAwMDJhNWQ1YzUxYi9odHMyMjEiLAogICAgICAgICJub2RlIjogIiIKICAgICAgfQogICAgfQogIH0sCiAgewogICAgInVpZCI6ICJmMWY3M2I1ZC0zNTg0LTJlYTQtM2M1OS01ZGUxYmRhNjRjYzMiLAogICAgIm5vZGUiOiAiIiwKICAgICJuYW1lIjogIklMUFMyMlFTIiwKICAgICJtb2RlbCI6ICJpbHBzMjJxcyIsCiAgICAibWFudWZhY3R1cmVyIjogIlNUTWljcm9lbGVjcm9uaWNzIiwKICAgICJtYXJrZXQiOiAiSW5kdXN0cmlhbCIsCiAgICAidHlwZSI6IHsKICAgICAgInNlbnNvckNhdGVnb3J5IjogIkVudmlyb25tZW50YWwiLAogICAgICAic2Vuc29yVHlwZSI6IFsiUHJlc3N1cmUiXQogICAgfSwKICAgICJzYW1wbGluZ1JhdGUiOiAiMSIsCiAgICAiYWNjdXJhY3kiOiBbIjAuMSJdLAogICAgImNvbnN1bXB0aW9uIjogIjAuMDUiLAogICAgImxhdGVuY3kiOiAiMTAwIiwKICAgICJwcm9wZXJ0aWVzIjogewogICAgICAidW5pdCI6IHsKICAgICAgICAibWVhc3VyZW1lbnQiOiBbImhQYSJdLAogICAgICAgICJjb25zdW1wdGlvbiI6ICJtVyIsCiAgICAgICAgInNhbXBsaW5nUmF0ZSI6ICJIeiIsCiAgICAgICAgImxhdGVuY3kiOiAibXMiCiAgICAgIH0KICAgIH0sCiAgICAiYWNjZXNzIjogewogICAgICAidHlwZSI6ICJNUVRUIiwKICAgICAgInNvdXJjZSI6ICJldmVudGJ1cy1mbHVpZG9zIiwKICAgICAgInJlc291cmNlIjogewogICAgICAgICJ0b3BpYyI6ICJzZW5zb3JzL0NCQjhDMjE1MTlFRi8wMDE0MDAwMDAwMDExMWUxYWMzNjAwMDJhNWQ1YzUxYi9pbHBzMjJxcyIsCiAgICAgICAgIm5vZGUiOiAiIgogICAgICB9CiAgICB9CiAgfQpd
spec:
  deviceModelRef:
    name: bluenrg
  protocol:
    bluetooth:
      macAddress: 00:11:22:33:FF:EE 
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: ''
        operator: In
        values:
        - fluidos-provider-1-edge-worker2          #pls give your edge node name
  propertyVisitors:
    - propertyName: environmental
      collectCycle: 500000000
      reportCycle: 1000000000    
      bluetooth:
        characteristicUUID: 00140000000111e1ac360002a5d5c51b
        dataConverter:
         startIndex: 2
         endIndex: 7
         orderOfOperations:  
    - propertyName: config
      bluetooth:
        characteristicUUID: 00f00000000111e1ac360002a5d5c51b
#        dataWrite:
#         "config": [10] #Here "Config" refers to the value of the property "config" and [10] refers to the corresponding []byte value to be written into the device when the value of config is "Config"      
           
  data:
    dataTopic: "$ke/events/device/+/data/update"
    dataProperties:
      - propertyName: environmental
        metadata:
          type: integer                
status:
  twins:
    - propertyName: environmental
    - propertyName: config
      desired:
        metadata:
          type: string
        value: "config"
      reported:
        metadata:
          type: string
        value: "0"

