{{- $eresManagerConfig := (merge (dict "name" "edge-resource-manager" "module" "edge-resource-manager") .) -}}

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "fluidos.prefixedName" $eresManagerConfig }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
spec:
  dnsNames:
  - {{ include "fluidos.prefixedName" $eresManagerConfig }}.{{ .Release.Namespace }}.svc
  - {{ include "fluidos.prefixedName" $eresManagerConfig }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ .Values.webhook.Issuer | default "self-signed" }}
  secretName: {{ include "fluidos.prefixedName" $eresManagerConfig }}